const express = require("express");
const { list, create, read, update, del } = require("../Controllers/product");
const { auth } = require("../middleware/auth");
const router = express.Router();
router.post("/productlist", auth, list);
router.get("/product/:id", auth, read);
router.post("/product", auth, create);
router.put("/product/:id", auth, update);
router.delete("/product/:id", auth, del);
module.exports = router;
